# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ad0f4c9591bf80d6475d89684a55f9a6ebd650204a0b054c2fb91f203881ffffd82cbd347dbac83ffd63eff169e903c6e83cc90d26bfaba56bc0c83315cf51
test:
  secret_key_base: c0a5430b3b18702ff61eafdcc069157e2eea89bc09d3e3299fdfd95558e7aae3c5f3470e0b073cb0b8722109508414a7e330371f20f23467a3f250beed32b343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>